import { CityInfo, NobarVenue } from '@/types'

export const CITY_LIST: CityInfo[] = [
  {
    slug: 'yogyakarta', name: 'Yogyakarta', emoji: '🏛️', province: 'DI Yogyakarta',
    description: 'Kota pelajar yang punya tradisi nobar paling meriah — dari Alun-alun Kidul yang legendaris sampai kafe-kafe estetik di Kaliurang.',
  },
  {
    slug: 'jakarta', name: 'Jakarta', emoji: '🏙️', province: 'DKI Jakarta',
    description: 'Ibu kota dengan venue nobar terlengkap — GBK Fan Zone, sports bar SCBD, sampai nonton bareng komunitas di berbagai penjuru kota.',
  },
  {
    slug: 'surabaya', name: 'Surabaya', emoji: '🦈', province: 'Jawa Timur',
    description: 'Kota Pahlawan dengan semangat suporter yang tinggi — Taman Bungkul, Pakuwon, sampai warung kopi Sidoarjo bisa jadi arena nobar.',
  },
  {
    slug: 'bandung', name: 'Bandung', emoji: '🌄', province: 'Jawa Barat',
    description: 'Kota kreatif dengan banyak kafe dan ruang komunitas — Braga, Dago, Buah Batu jadi pusat nobar paling seru di Jawa Barat.',
  },
  {
    slug: 'medan', name: 'Medan', emoji: '🌴', province: 'Sumatera Utara',
    description: 'Kota terbesar Sumatera dengan komunitas bola yang solid — Lapangan Merdeka sampai kafe-kafe Sun Plaza jadi tempat favorit nobar.',
  },
  {
    slug: 'makassar', name: 'Makassar', emoji: '🌊', province: 'Sulawesi Selatan',
    description: 'Kota Daeng dengan suporter fanatik — nobar di Pantai Losari dengan sunset dan ribuan orang adalah pengalaman yang tidak terlupakan.',
  },
  {
    slug: 'semarang', name: 'Semarang', emoji: '⛵', province: 'Jawa Tengah',
    description: 'Kota Atlas dengan kawasan Kota Lama yang ikonik — banyak kafe dan komunitas yang rutin gelar nobar saat pertandingan besar.',
  },
  {
    slug: 'malang', name: 'Malang', emoji: '🍎', province: 'Jawa Timur',
    description: 'Kota dingin dengan suporter Arema yang passionate — venue nobar dari alun-alun sampai kafe-kafe hits di Jalan Ijen.',
  },
  {
    slug: 'solo', name: 'Solo', emoji: '🎭', province: 'Jawa Tengah',
    description: 'Kota Batik yang tenang tapi punya tradisi nobar yang kuat — Sriwedari sampai kafe-kafe Laweyan jadi pilihan favorit warga Solo.',
  },
  {
    slug: 'denpasar', name: 'Denpasar', emoji: '🏖️', province: 'Bali',
    description: 'Ibukota Bali dengan perpaduan wisatawan dan lokal — sports bar Seminyak sampai komunitas nobar di Denpasar siap menyambut bola dunia.',
  },
  {
    slug: 'palembang', name: 'Palembang', emoji: '🌉', province: 'Sumatera Selatan',
    description: 'Kota Pempek dengan Jembatan Ampera yang ikonik — venue nobar dari pinggiran Musi sampai mall-mall di pusat kota.',
  },
  {
    slug: 'balikpapan', name: 'Balikpapan', emoji: '🛢️', province: 'Kalimantan Timur',
    description: 'Kota Minyak dengan komunitas ekspat dan lokal yang aktif — sports bar dan kafe-kafe modern jadi arena nobar Piala Dunia.',
  },
  {
    slug: 'pekanbaru', name: 'Pekanbaru', emoji: '🦁', province: 'Riau',
    description: 'Ibu kota Riau yang berkembang pesat — kafe modern dan komunitas bola aktif menjadikan Pekanbaru kota nobar yang tidak boleh diremehkan.',
  },
  {
    slug: 'pontianak', name: 'Pontianak', emoji: '🌐', province: 'Kalimantan Barat',
    description: 'Kota khatulistiwa dengan semangat nobar yang membara — tepian Sungai Kapuas jadi spot legendaris nonton bareng warga Pontianak.',
  },
  {
    slug: 'manado', name: 'Manado', emoji: '🌺', province: 'Sulawesi Utara',
    description: 'Kota di ujung utara Sulawesi yang dikenal ceria dan ramah — komunitas nobar Manado selalu meriah di pinggir Teluk Manado.',
  },
  {
    slug: 'samarinda', name: 'Samarinda', emoji: '🌿', province: 'Kalimantan Timur',
    description: 'Ibu kota Kalimantan Timur yang dekat dengan IKN — tradisi nobar warga Samarinda sudah mengakar kuat di tepian Sungai Mahakam.',
  },
]

export function getCityBySlug(slug: string): CityInfo | undefined {
  return CITY_LIST.find(c => c.slug === slug)
}

export const VENUES: NobarVenue[] = [
  // ── YOGYAKARTA ──────────────────────────────────────────────
  {
    id: 'yk-1',
    name: 'Nobar Alun-alun Kidul',
    city: 'yogyakarta',
    address: 'Alun-alun Kidul, Kraton, Yogyakarta 55131',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Layar LED Besar', 'Food Court', 'Parkir Luas', 'Keluarga'],
    isFree: true,
    openTime: '19.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Alun-alun+Kidul+Yogyakarta',
    websiteUrl: 'https://instagram.com/pemkotjogja',
    description: 'Venue nobar paling ikonik di Yogyakarta. Layar LED besar dipasang menghadap kerumunan, suasana ramai dan meriah. Tersedia banyak pedagang makanan dan minuman di sekitar. Cocok untuk keluarga maupun komunitas besar. Akses mudah dari Malioboro, parkir luas tersedia.',
  },
  {
    id: 'yk-2',
    name: 'Filosofi Kopi Yogyakarta',
    city: 'yogyakarta',
    address: 'Jl. Ndalem Mangkubumen KT III/578, Ngampilan, Yogyakarta',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'Proyektor 150"', 'Reservasi', 'WiFi', 'Kopi Specialty'],
    isFree: false,
    openTime: '08.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Filosofi+Kopi+Yogyakarta',
    phone: '0274-562222',
    websiteUrl: 'https://instagram.com/filosofikopijogja',
    description: 'Kafe ikonik dari novel dan film Filosofi Kopi. Proyektor besar untuk nobar dengan gambar jernih. Suasana nyaman dan estetik, menu kopi specialty Nusantara pilihan. Disarankan reservasi untuk pertandingan besar. Minimum order berlaku saat event.',
  },
  {
    id: 'yk-3',
    name: 'Angkringan Lik Man',
    city: 'yogyakarta',
    address: 'Jl. Wongsodirjan, dekat Stasiun Tugu, Yogyakarta',
    type: 'outdoor',
    icon: '🍗',
    tags: ['Murah Meriah', 'Kopi Joss', 'Nasi Kucing', 'Buka Dini Hari'],
    isFree: true,
    openTime: '17.00–03.00',
    mapsUrl: 'https://maps.google.com/?q=Angkringan+Lik+Man+Yogyakarta',
    description: 'Angkringan legendaris buka dari sore hingga dini hari — pas untuk nobar pertandingan malam Eropa. Harga sangat terjangkau, menu nasi kucing dan kopi joss khas Jogja. Layar TV dipasang saat ada pertandingan besar. Suasana khas Jogja yang santai dan akrab.',
  },
  {
    id: 'yk-4',
    name: 'Warung Kopi Klotok',
    city: 'yogyakarta',
    address: 'Jl. Kaliurang KM 16, Pakem, Sleman, Yogyakarta',
    type: 'cafe',
    icon: '🌄',
    tags: ['View Merapi', 'Outdoor', 'WiFi', 'Suasana Alam'],
    isFree: true,
    openTime: '06.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Warung+Kopi+Klotok+Yogyakarta',
    description: 'Warung kopi dengan view Gunung Merapi. Area outdoor luas dengan layar TV untuk nobar santai sambil menikmati udara pegunungan Kaliurang. Menu sarapan dan makan siang tersedia, harga sangat terjangkau.',
  },
  {
    id: 'yk-5',
    name: 'Soccer Cafe Ambarukmo',
    city: 'yogyakarta',
    address: 'Jl. Laksda Adisucipto, Ambarukmo, Sleman',
    type: 'cafe',
    icon: '⚽',
    tags: ['AC', 'Multi Screen', 'Live Score', 'Buka Malam'],
    isFree: false,
    openTime: '16.00–02.00',
    mapsUrl: 'https://maps.google.com/?q=Ambarukmo+Yogyakarta',
    phone: '0274-485858',
    description: 'Sports cafe khusus bola di kawasan Ambarukmo. Beberapa layar besar bisa menayangkan pertandingan berbeda sekaligus. Menu makanan dan minuman lengkap, suasana sporty. Cocok untuk nobar ramai dengan komunitas.',
  },
  {
    id: 'yk-6',
    name: 'Komunitas Bola Jogja (KBJ)',
    city: 'yogyakarta',
    address: 'Sekretariat: Jl. Colombo No.1, Karangmalang, Sleman',
    type: 'komunitas',
    icon: '⚽',
    tags: ['Komunitas', 'Gratis', 'WhatsApp Group', 'Semua Level'],
    isFree: true,
    openTime: 'Sesuai jadwal pertandingan',
    mapsUrl: 'https://maps.google.com/?q=Colombo+Yogyakarta',
    description: 'Komunitas pecinta bola Yogyakarta yang aktif menggelar nobar setiap pertandingan besar. Tempat nobar bervariasi sesuai kesepakatan anggota. Gabung via WhatsApp Group untuk info jadwal. Terbuka untuk semua kalangan.',
  },
  {
    id: 'yk-7',
    name: 'Kafe Buku Kopi Merapi',
    city: 'yogyakarta',
    address: 'Jl. Kaliurang KM 8, Ngaglik, Sleman',
    type: 'cafe',
    icon: '📚',
    tags: ['Buku', 'AC', 'WiFi', 'Proyektor', 'Tenang'],
    isFree: false,
    openTime: '09.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Kaliurang+Sleman+Yogyakarta',
    description: 'Kafe unik perpaduan buku dan kopi di jalan Kaliurang. Proyektor tersedia untuk nobar dengan suasana tenang dan intelektual. Cocok untuk nobar kelas kecil dengan teman diskusi. Kopi single origin Nusantara dan makanan ringan tersedia.',
  },

  // ── JAKARTA ─────────────────────────────────────────────────
  {
    id: 'jkt-1',
    name: 'Fan Zone GBK Senayan',
    city: 'jakarta',
    address: 'Pintu 1 Stadion Utama GBK, Senayan, Jakarta Pusat',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Layar LED Raksasa', 'Food Festival', 'Kapasitas 5000+', 'Gratis', 'KRL Palmerah'],
    isFree: true,
    openTime: '18.00–01.00',
    mapsUrl: 'https://maps.google.com/?q=GBK+Senayan+Jakarta',
    websiteUrl: 'https://instagram.com/gbk.indonesia',
    phone: '021-5703990',
    description: 'Fan zone resmi di kawasan GBK Senayan — venue nobar terbesar di Jakarta. Layar LED raksasa kualitas broadcast profesional. Ratusan tenant F&B, hiburan live, dan area sponsor. Aktif saat Piala Dunia dan Euro. Akses KRL dari Stasiun Palmerah atau MRT Senayan.',
  },
  {
    id: 'jkt-2',
    name: 'Anomali Coffee Senopati',
    city: 'jakarta',
    address: 'Jl. Senopati No.14, Kebayoran Baru, Jakarta Selatan',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'Proyektor 4K', 'Specialty Coffee', 'Reservasi', 'WiFi'],
    isFree: false,
    openTime: '08.00–00.00',
    mapsUrl: 'https://maps.google.com/?q=Anomali+Coffee+Senopati+Jakarta',
    phone: '021-27537123',
    websiteUrl: 'https://instagram.com/anomalicoffee',
    description: 'Kafe specialty coffee premium di Senopati. Layar 4K untuk nobar suasana premium. Minimum order berlaku. Cocok untuk nobar eksklusif dengan kolega. Menu makanan lengkap dan mocktail pilihan.',
  },
  {
    id: 'jkt-3',
    name: 'M Bloc Space Jakarta',
    city: 'jakarta',
    address: 'Jl. Panglima Polim V No.2, Kebayoran Baru, Jakarta Selatan',
    type: 'outdoor',
    icon: '📽️',
    tags: ['Outdoor', 'Komunitas', 'Anak Muda', 'Food Truck', 'Vibe Berbeda'],
    isFree: true,
    openTime: '12.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=M+Bloc+Space+Jakarta',
    websiteUrl: 'https://instagram.com/mblocspace',
    description: 'Creative space multifungsi di Kebayoran yang sering gelar nobar tematik. Industrial-chic dengan outdoor area luas. Food truck dan bar tersedia. Cocok untuk anak muda yang mau nobar dengan vibes berbeda dari biasanya.',
  },
  {
    id: 'jkt-4',
    name: 'Sports Bar Kemang',
    city: 'jakarta',
    address: 'Jl. Kemang Raya No.45, Kemang, Jakarta Selatan',
    type: 'resto',
    icon: '🍺',
    tags: ['Sports Bar', 'Multi Screen', 'AC', 'Buka Malam', 'Internasional'],
    isFree: false,
    openTime: '17.00–03.00',
    mapsUrl: 'https://maps.google.com/?q=Kemang+Raya+Jakarta',
    description: 'Sports bar di Kemang dengan puluhan layar yang menayangkan berbagai pertandingan sekaligus. Atmosfer internasional, cocok untuk komunitas ekspat dan lokal. Menu bar lengkap, makanan Barat dan Asia. Selalu penuh saat big match.',
  },
  {
    id: 'jkt-5',
    name: 'Taman Menteng',
    city: 'jakarta',
    address: 'Jl. HOS. Cokroaminoto, Menteng, Jakarta Pusat',
    type: 'outdoor',
    icon: '🌳',
    tags: ['Gratis', 'Pusat Kota', 'Transportasi Umum', 'Keluarga'],
    isFree: true,
    openTime: '07.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Taman+Menteng+Jakarta',
    description: 'Taman kota di jantung Jakarta yang sering jadi titik kumpul nobar komunitas. Akses mudah dari berbagai penjuru Jakarta, dekat halte TransJakarta. Saat Piala Dunia komunitas sering menggelar layar tancap outdoor di area ini.',
  },
  {
    id: 'jkt-6',
    name: 'Kopi Kenangan SCBD',
    city: 'jakarta',
    address: 'Pacific Place Mall, SCBD, Jakarta Selatan',
    type: 'mall',
    icon: '🏢',
    tags: ['AC', 'Indoor', 'Office Area', 'WiFi', 'Modern'],
    isFree: false,
    openTime: '07.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Pacific+Place+SCBD+Jakarta',
    description: 'Nobar premium di kawasan bisnis SCBD. Beberapa kafe dan restoran di Pacific Place memasang layar besar saat pertandingan. Suasana profesional cocok untuk nobar dengan rekan kerja. Akses mudah dari MRT ASEAN.',
  },

  // ── SURABAYA ────────────────────────────────────────────────
  {
    id: 'sby-1',
    name: 'Taman Bungkul',
    city: 'surabaya',
    address: 'Jl. Raya Darmo, Wonokromo, Surabaya',
    type: 'outdoor',
    icon: '🌳',
    tags: ['Gratis', 'Outdoor', 'Layar LED', 'Keluarga', 'Akses Mudah'],
    isFree: true,
    openTime: '18.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Taman+Bungkul+Surabaya',
    websiteUrl: 'https://instagram.com/pemkot_surabaya',
    description: 'Taman kota paling populer di Surabaya untuk nobar gratis. Layar LED di area terbuka, fasilitas toilet tersedia. Strategis di Jalan Darmo, mudah diakses. Atmosphere seru dan ramai saat pertandingan besar.',
  },
  {
    id: 'sby-2',
    name: 'G-Walk Citraland',
    city: 'surabaya',
    address: 'G-Walk, CitraLand, Surabaya Barat',
    type: 'resto',
    icon: '🍽️',
    tags: ['Outdoor Kuliner', 'Keluarga', 'Pilihan F&B Banyak', 'Parkir Luas'],
    isFree: true,
    openTime: '17.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=G-Walk+Citraland+Surabaya',
    description: 'Kawasan kuliner outdoor di CitraLand dengan berbagai restoran dan kafe. Beberapa outlet pasang layar besar saat pertandingan. Pilihan makanan sangat beragam dari semua harga, cocok untuk keluarga.',
  },
  {
    id: 'sby-3',
    name: 'Monumen Kapal Selam (Monkasel)',
    city: 'surabaya',
    address: 'Jl. Pemuda No.39, Embong Kaliasin, Surabaya',
    type: 'outdoor',
    icon: '⚓',
    tags: ['Ikonik', 'Gratis', 'Pusat Kota', 'Layar Besar'],
    isFree: true,
    openTime: '18.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Monumen+Kapal+Selam+Surabaya',
    description: 'Area terbuka di sekitar Monkasel yang sering jadi spot nobar komunitas Surabaya. Lokasi sangat strategis di pusat kota. Saat Piala Dunia biasanya ada layar besar dari komunitas atau sponsor.',
  },
  {
    id: 'sby-4',
    name: 'Pakuwon Mall Food Court',
    city: 'surabaya',
    address: 'Jl. Puncak Indah Lontar No.2, Surabaya Barat',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Terlengkap'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Pakuwon+Mall+Surabaya',
    description: 'Food court terbesar di Surabaya Barat yang memasang layar besar saat ada pertandingan. Ber-AC nyaman, pilihan makanan dari seluruh Indonesia tersedia. Parkir luas, cocok untuk keluarga dengan anak.',
  },

  // ── BANDUNG ─────────────────────────────────────────────────
  {
    id: 'bdg-1',
    name: 'The Mates Football & Dining',
    city: 'bandung',
    address: 'Jl. Braga No.11, Sumur Bandung, Bandung',
    type: 'cafe',
    icon: '⚽',
    tags: ['Multi Screen', 'Live DJ', 'AC', 'Buka Malam', 'Reservasi'],
    isFree: false,
    openTime: '18.00–03.00',
    mapsUrl: 'https://maps.google.com/?q=Braga+Bandung',
    websiteUrl: 'https://instagram.com/the.mates.football',
    description: 'Sports cafe bertema sepakbola di kawasan Braga. Multi layar besar dari berbagai sudut. DJ sebelum kick-off dan halftime. Reservasi sangat disarankan untuk big match. Menu Western dan lokal tersedia.',
  },
  {
    id: 'bdg-2',
    name: 'Alun-alun Bandung',
    city: 'bandung',
    address: 'Jl. Asia Afrika, Balonggede, Bandung',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Gratis', 'Rumput Sintetis', 'Pusat Kota', 'Keluarga', 'Trans Metro'],
    isFree: true,
    openTime: '06.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Alun-alun+Bandung',
    description: 'Alun-alun kota Bandung dengan rumput sintetis terkenal. Saat Piala Dunia sering digelar nobar besar dengan layar raksasa. Dekat Masjid Agung, Gedung Sate, dan jalur Trans Metro Bandung.',
  },
  {
    id: 'bdg-3',
    name: 'Dago Dream Park',
    city: 'bandung',
    address: 'Jl. Dago Giri No.88, Mekarwangi, Lembang',
    type: 'outdoor',
    icon: '🌄',
    tags: ['View Kota Bandung', 'Outdoor Malam', 'Instagramable', 'Udara Sejuk'],
    isFree: false,
    openTime: '10.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Dago+Dream+Park+Bandung',
    phone: '022-82776868',
    websiteUrl: 'https://instagram.com/dagodreampark',
    description: 'Taman di dataran tinggi Dago dengan pemandangan kota Bandung spektakuler. Layar outdoor dengan backdrop kota yang indah. Pengalaman nobar yang benar-benar berbeda, udara sejuk khas Bandung atas.',
  },
  {
    id: 'bdg-4',
    name: 'Buah Batu Square',
    city: 'bandung',
    address: 'Jl. Buah Batu No.147, Turangga, Bandung',
    type: 'cafe',
    icon: '☕',
    tags: ['Kawasan Kafe', 'AC', 'WiFi', 'Anak Muda', 'Live Music'],
    isFree: false,
    openTime: '10.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Buah+Batu+Bandung',
    description: 'Kawasan kafe terpopuler di Bandung Selatan. Banyak kafe di sini yang pasang layar besar saat ada pertandingan. Vibes anak muda kota, live music tersedia di beberapa tempat. Pilihan kuliner sangat beragam.',
  },

  // ── MEDAN ───────────────────────────────────────────────────
  {
    id: 'mdn-1',
    name: 'Lapangan Merdeka Medan',
    city: 'medan',
    address: 'Jl. Balai Kota, Kesawan, Medan Barat',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Gratis', 'Layar LED', 'Pusat Kota', 'Kapasitas Ribuan'],
    isFree: true,
    openTime: '17.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Lapangan+Merdeka+Medan',
    description: 'Lapangan bersejarah pusat kota Medan untuk nobar skala besar. Layar LED dipasang menghadap ribuan penonton. Dekat kuliner legendaris Medan: warung nasi goreng dan sop kambing khas Kesawan.',
  },
  {
    id: 'mdn-2',
    name: 'Sun Plaza Medan',
    city: 'medan',
    address: 'Jl. Haji Zainul Arifin No.7, Petisah Tengah, Medan',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Parkir Luas'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Sun+Plaza+Medan',
    description: 'Mall premium pusat kota Medan. Food court dan beberapa restoran pasang layar besar saat pertandingan besar. Ber-AC, pilihan makanan beragam termasuk kuliner khas Medan.',
  },
  {
    id: 'mdn-3',
    name: 'Warung Kopi Saring',
    city: 'medan',
    address: 'Jl. Sei Batanghari, Medan Petisah',
    type: 'cafe',
    icon: '☕',
    tags: ['Kopi Sumatera', 'AC', 'WiFi', 'Proyektor', 'Mahasiswa'],
    isFree: false,
    openTime: '08.00–01.00',
    mapsUrl: 'https://maps.google.com/?q=Medan+Petisah',
    description: 'Kedai kopi Sumatera yang menjadi tempat nongkrong mahasiswa dan anak muda Medan. Proyektor tersedia saat pertandingan besar, kopi Mandailing dan Sidikalang berkualitas. Harga terjangkau dengan suasana hangat.',
  },

  // ── MAKASSAR ────────────────────────────────────────────────
  {
    id: 'mks-1',
    name: 'Pantai Losari',
    city: 'makassar',
    address: 'Jl. Penghibur, Losari, Ujung Pandang, Makassar',
    type: 'outdoor',
    icon: '🌊',
    tags: ['View Pantai', 'Gratis', 'Sunset Indah', 'Ikonik', 'Pisang Epe'],
    isFree: true,
    openTime: '18.00–00.00',
    mapsUrl: 'https://maps.google.com/?q=Pantai+Losari+Makassar',
    websiteUrl: 'https://instagram.com/pantailosari.makassar',
    description: 'Landmark paling ikonik Makassar. Nobar di sini dengan latar Selat Makassar adalah pengalaman tak terlupakan. Layar LED dipasang saat event besar. Puluhan kios pisang epe dan kuliner khas Makassar berjajar di sepanjang pantai.',
  },
  {
    id: 'mks-2',
    name: 'Trans Studio Mall Makassar',
    city: 'makassar',
    address: 'Jl. Metro Tanjung Bunga, Tanjung Merdeka, Makassar',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Indoor', 'Food Court', 'Keluarga', 'Trans Studio'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Trans+Studio+Mall+Makassar',
    description: 'Mall terbesar Makassar. Food court dan restoran pasang layar besar saat pertandingan. Ber-AC, cocok keluarga. Dekat Trans Studio Theme Park. Pilihan kuliner sangat beragam.',
  },
  {
    id: 'mks-3',
    name: 'Celebes Convention Center (CCC)',
    city: 'makassar',
    address: 'Jl. Metro Tanjung Bunga, Makassar',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Venue Besar', 'Gratis', 'Pantai', 'Komunitas'],
    isFree: true,
    openTime: '17.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Celebes+Convention+Center+Makassar',
    description: 'Area luar CCC yang menghadap perairan Makassar sering dijadikan venue nobar skala besar oleh komunitas dan pemerintah kota. Kapasitas ribuan orang, suasana outdoor dengan angin laut.',
  },

  // ── SEMARANG ────────────────────────────────────────────────
  {
    id: 'smg-1',
    name: 'Kota Lama Semarang',
    city: 'semarang',
    address: 'Kawasan Kota Lama, Semarang Utara',
    type: 'outdoor',
    icon: '🏛️',
    tags: ['Heritage', 'Gratis', 'Kuliner', 'Foto Instagramable', 'Komunitas'],
    isFree: true,
    openTime: '18.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Kota+Lama+Semarang',
    description: 'Kawasan bersejarah Semarang yang direvitalisasi jadi destinasi wisata dan kuliner. Komunitas gelar nobar outdoor di area pedestrian. Background bangunan Belanda membuat suasana nobar sangat berkarakter dan instagramable.',
  },
  {
    id: 'smg-2',
    name: 'Simpang Lima Semarang',
    city: 'semarang',
    address: 'Jl. Pahlawan, Mugassari, Semarang Selatan',
    type: 'outdoor',
    icon: '⭐',
    tags: ['Pusat Kota', 'Gratis', 'Akses Mudah', 'Keluarga', 'Layar Besar'],
    isFree: true,
    openTime: '18.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Simpang+Lima+Semarang',
    description: 'Alun-alun pusat kota Semarang yang jadi pusat keramaian saat event besar. Pemerintah kota terkadang pasang layar LED besar saat Piala Dunia. Dikelilingi hotel, pusat perbelanjaan, dan aneka kuliner.',
  },
  {
    id: 'smg-3',
    name: 'Paragon Mall Semarang',
    city: 'semarang',
    address: 'Jl. Pemuda No.118, Sekayu, Semarang Tengah',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Bioskop', 'Keluarga'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Paragon+Mall+Semarang',
    description: 'Mall premium di jantung Semarang. Food court dan area F&B memasang layar besar saat pertandingan. Ber-AC nyaman, fasilitas lengkap termasuk bioskop. Parkir luas tersedia.',
  },

  // ── MALANG ──────────────────────────────────────────────────
  {
    id: 'mlg-1',
    name: 'Alun-alun Malang',
    city: 'malang',
    address: 'Jl. Merdeka Barat, Kiduldalem, Klojen, Malang',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Gratis', 'Pusat Kota', 'Keluarga', 'Layar Besar', 'Kuliner Sekitar'],
    isFree: true,
    openTime: '18.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Alun-alun+Malang',
    description: 'Jantung kota Malang yang jadi venue nobar ribuan warga saat Piala Dunia. Layar besar dipasang, suasana sangat meriah. Dekat berbagai kuliner khas Malang: bakso President, es krim Toko Oen.',
  },
  {
    id: 'mlg-2',
    name: 'Kopi Joss Jl. Ijen',
    city: 'malang',
    address: 'Jl. Ijen No.77, Gading Kasri, Klojen, Malang',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'Proyektor', 'Jalan Ijen', 'WiFi', 'Kopi Pilihan'],
    isFree: false,
    openTime: '09.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Jalan+Ijen+Malang',
    description: 'Kafe di kawasan elite Jalan Ijen Malang dengan proyektor besar untuk nobar. Ber-AC dan cozy, kopi pilihan berkualitas. Cocok untuk nobar santai atau nonton bareng teman kampus.',
  },
  {
    id: 'mlg-3',
    name: 'Stadion Gajayana Area',
    city: 'malang',
    address: 'Jl. Gajayana, Dinoyo, Lowokwaru, Malang',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Area Stadion', 'Arema', 'Komunitas', 'Gratis'],
    isFree: true,
    openTime: '18.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Stadion+Gajayana+Malang',
    description: 'Area sekitar Stadion Gajayana yang jadi pusat komunitas Arema. Saat ada pertandingan besar, aremania sering gelar nobar di area ini. Suasana sangat solid dan penuh semangat.',
  },

  // ── SOLO ────────────────────────────────────────────────────
  {
    id: 'slo-1',
    name: 'Sriwedari Solo',
    city: 'solo',
    address: 'Jl. Slamet Riyadi No.275, Sriwedari, Solo',
    type: 'outdoor',
    icon: '🎭',
    tags: ['Gratis', 'Taman Kota', 'Keluarga', 'Bersejarah', 'Slamet Riyadi'],
    isFree: true,
    openTime: '16.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Sriwedari+Solo',
    description: 'Taman budaya bersejarah di jantung Solo yang jadi venue acara publik termasuk nobar. Area terbuka luas, khas Solo yang tenang namun meriah. Dekat Jalan Slamet Riyadi yang penuh kuliner legendaris.',
  },
  {
    id: 'slo-2',
    name: 'Ngarsopuro Night Market',
    city: 'solo',
    address: 'Jl. Diponegoro, Keprabon, Banjarsari, Solo',
    type: 'outdoor',
    icon: '🌙',
    tags: ['Malam', 'Kuliner Tradisional', 'Outdoor', 'Mangkunegaran'],
    isFree: true,
    openTime: '18.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Ngarsopuro+Solo',
    description: 'Pasar malam di depan Pura Mangkunegaran aktif tiap Sabtu. Beberapa warung pasang TV untuk nobar. Suasana otentik Solo dengan kuliner tradisional: serabi dan wedang jahe khas.',
  },
  {
    id: 'slo-3',
    name: 'Solo Grand Mall Area',
    city: 'solo',
    address: 'Jl. Slamet Riyadi No.273, Sriwedari, Solo',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Pusat Kota'],
    isFree: true,
    openTime: '10.00–21.30',
    mapsUrl: 'https://maps.google.com/?q=Solo+Grand+Mall',
    description: 'Pusat perbelanjaan di Jalan Slamet Riyadi dengan food court yang memasang layar besar saat ada pertandingan. Ber-AC, pilihan kuliner lengkap, parkir tersedia.',
  },

  // ── DENPASAR / BALI ─────────────────────────────────────────
  {
    id: 'dps-1',
    name: 'Sports Bar Seminyak',
    city: 'denpasar',
    address: 'Jl. Laksmana (Oberoi), Seminyak, Kuta Utara, Bali',
    type: 'cafe',
    icon: '🏖️',
    tags: ['Expat Friendly', 'Buka Dini Hari', 'AC', 'Multi Screen', 'Internasional'],
    isFree: false,
    openTime: '12.00–04.00',
    mapsUrl: 'https://maps.google.com/?q=Seminyak+Bali',
    websiteUrl: 'https://instagram.com/seminyak_bali',
    description: 'Kawasan Seminyak dikenal dengan sports bar berkualitas internasional yang selalu putar semua pertandingan besar. Suasana kosmopolitan, campuran wisatawan dan ekspat. Bisa sampai dini hari saat big match.',
  },
  {
    id: 'dps-2',
    name: 'Lapangan Puputan Margarana',
    city: 'denpasar',
    address: 'Jl. Surapati, Dangin Puri, Denpasar Timur',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Gratis', 'Pusat Kota Denpasar', 'Keluarga', 'Lokal Bali'],
    isFree: true,
    openTime: '17.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Lapangan+Puputan+Denpasar',
    description: 'Lapangan bersejarah pusat Denpasar untuk nobar gratis warga lokal. Layar besar sering dipasang pemerintah kota saat Piala Dunia. Suasana lokal Bali yang autentik, jauh dari keramaian turis Kuta.',
  },
  {
    id: 'dps-3',
    name: 'Warung Mak Beng',
    city: 'denpasar',
    address: 'Jl. Hang Tuah No.45, Sanur, Denpasar Selatan',
    type: 'resto',
    icon: '🐟',
    tags: ['Kuliner Bali', 'Legendaris', 'Ikan Goreng', 'TV'],
    isFree: false,
    openTime: '08.00–20.00',
    mapsUrl: 'https://maps.google.com/?q=Warung+Mak+Beng+Sanur+Bali',
    phone: '0361-282633',
    description: 'Warung ikan goreng legendaris di Sanur yang buka sejak 1941. Pasang TV saat ada pertandingan, pengalaman nobar sambil menikmati ikan goreng Bali yang terkenal. Suasana warung lokal yang hangat dan otentik.',
  },

  // ── PALEMBANG ───────────────────────────────────────────────
  {
    id: 'plb-1',
    name: 'Benteng Kuto Besak',
    city: 'palembang',
    address: 'Jl. Rumah Bari, 19 Ilir, Bukit Kecil, Palembang',
    type: 'outdoor',
    icon: '🌉',
    tags: ['View Sungai Musi', 'Gratis', 'Ikonik', 'Malam', 'Pempek'],
    isFree: true,
    openTime: '18.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Benteng+Kuto+Besak+Palembang',
    websiteUrl: 'https://instagram.com/kotapalembang',
    description: 'Area benteng bersejarah tepi Sungai Musi dengan view Jembatan Ampera spektakuler. Layar LED dipasang menghadap sungai saat big match. Tersedia berbagai penjual pempek dan makanan khas Palembang.',
  },
  {
    id: 'plb-2',
    name: 'Palembang Icon Mall',
    city: 'palembang',
    address: 'Jl. POM IX, Ario Kemuning, Palembang',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Indoor', 'Food Court', 'Keluarga', 'Bioskop'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Palembang+Icon+Mall',
    description: 'Mall terbesar Palembang dengan food court modern yang pasang layar besar saat pertandingan. Ber-AC, pilihan makanan beragam termasuk khas Palembang. Parkir luas.',
  },
  {
    id: 'plb-3',
    name: 'Warung Kopi Pempek 26',
    city: 'palembang',
    address: 'Jl. Sudirman, Ilir Timur, Palembang',
    type: 'resto',
    icon: '🐟',
    tags: ['Pempek', 'Kopi', 'Layar TV', 'Lokal', 'Terjangkau'],
    isFree: false,
    openTime: '07.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Sudirman+Palembang',
    description: 'Warung kopi legendaris di Sudirman yang jadi favorit warga Palembang. Menu pempek, tekwan, dan kopi khas Sumatera Selatan. Layar TV besar dipasang saat ada pertandingan, suasana hangat dan akrab.',
  },

  // ── BALIKPAPAN ──────────────────────────────────────────────
  {
    id: 'bpp-1',
    name: 'Pantai Manggar',
    city: 'balikpapan',
    address: 'Jl. Mulawarman, Lamaru, Balikpapan Timur',
    type: 'outdoor',
    icon: '🏖️',
    tags: ['Pantai', 'Gratis', 'Sunset', 'Keluarga', 'Outdoor'],
    isFree: true,
    openTime: '17.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Pantai+Manggar+Balikpapan',
    description: 'Pantai paling populer di Balikpapan. Komunitas lokal sering gelar nobar outdoor saat pertandingan malam. Banyak warung makanan, suasana santai. Panorama laut jadi backdrop nobar yang indah.',
  },
  {
    id: 'bpp-2',
    name: 'Big Mall Balikpapan',
    city: 'balikpapan',
    address: 'Jl. Jenderal Sudirman, Gunung Sari Ulu, Balikpapan',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Bioskop'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Big+Mall+Balikpapan',
    description: 'Mall terbesar dan terlengkap di Balikpapan. Food court di lantai atas pasang layar besar saat pertandingan. Ber-AC nyaman, pilihan kuliner lengkap. Cocok untuk keluarga atau grup kantor.',
  },
  {
    id: 'bpp-3',
    name: 'Kafe Kilang Balikpapan',
    city: 'balikpapan',
    address: 'Jl. MT. Haryono, Balikpapan Tengah',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'WiFi', 'Proyektor', 'Komunitas Ekspat', 'Kopi'],
    isFree: false,
    openTime: '09.00–01.00',
    mapsUrl: 'https://maps.google.com/?q=Haryono+Balikpapan',
    description: 'Kafe modern di pusat Balikpapan yang jadi favorit komunitas ekspat migas. Proyektor besar untuk nobar, WiFi kencang, kopi specialty pilihan. Buka sampai dini hari — pas untuk pertandingan jam ganjil.',
  },

  // ── PEKANBARU ───────────────────────────────────────────────
  {
    id: 'pkb-1',
    name: 'Taman Kota Pekanbaru',
    city: 'pekanbaru',
    address: 'Jl. Diponegoro, Pekanbaru',
    type: 'outdoor',
    icon: '🌳',
    tags: ['Gratis', 'Pusat Kota', 'Keluarga', 'Komunitas'],
    isFree: true,
    openTime: '17.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Taman+Kota+Pekanbaru',
    description: 'Taman kota di pusat Pekanbaru yang jadi titik kumpul warga untuk nobar. Komunitas bola Pekanbaru aktif gelar screening outdoor saat pertandingan besar. Suasana ramai dan bersahabat.',
  },
  {
    id: 'pkb-2',
    name: 'SKA Co Ex Mall',
    city: 'pekanbaru',
    address: 'Jl. Soekarno Hatta, Pekanbaru',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Modern'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=SKA+Mall+Pekanbaru',
    description: 'Mall modern Pekanbaru dengan food court dan restoran yang memasang layar besar saat pertandingan. Ber-AC, pilihan makanan lengkap. Parkir luas tersedia.',
  },
  {
    id: 'pkb-3',
    name: 'Kafe Riau Ekspress',
    city: 'pekanbaru',
    address: 'Jl. Sudirman, Pekanbaru',
    type: 'cafe',
    icon: '☕',
    tags: ['Kopi Robusta Riau', 'AC', 'WiFi', 'Proyektor', 'Mahasiswa'],
    isFree: false,
    openTime: '08.00–00.00',
    mapsUrl: 'https://maps.google.com/?q=Sudirman+Pekanbaru',
    description: 'Kafe dengan kopi robusta khas Riau yang jadi favorit mahasiswa Pekanbaru. Proyektor tersedia untuk nobar, suasana hangat dan akrab. WiFi kencang, cocok untuk nobar sambil nongkrong panjang.',
  },

  // ── PONTIANAK ───────────────────────────────────────────────
  {
    id: 'ptk-1',
    name: 'Tepian Sungai Kapuas',
    city: 'pontianak',
    address: 'Jl. Tanjungpura, Pontianak Kota',
    type: 'outdoor',
    icon: '🌐',
    tags: ['View Kapuas', 'Gratis', 'Ikonik', 'Malam', 'Kuliner Tepian'],
    isFree: true,
    openTime: '18.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Tepian+Kapuas+Pontianak',
    websiteUrl: 'https://instagram.com/terimakasihjogja',
    description: 'Tepian Sungai Kapuas adalah jantung Pontianak — venue nobar dengan view sungai terbesar di Indonesia. Layar LED dipasang saat event besar, suasana sejuk di tepi sungai dengan kuliner khas Pontianak tersedia.',
  },
  {
    id: 'ptk-2',
    name: 'Mal Pontianak',
    city: 'pontianak',
    address: 'Jl. Rahadi Osman, Pontianak Kota',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Pusat Kota'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Mal+Pontianak',
    description: 'Pusat perbelanjaan utama Pontianak dengan food court yang pasang layar besar saat pertandingan. Ber-AC, pilihan kuliner termasuk makanan khas Pontianak. Lokasi strategis di pusat kota.',
  },
  {
    id: 'ptk-3',
    name: 'Warung Kopi Asiang',
    city: 'pontianak',
    address: 'Jl. Merapi, Pontianak Utara',
    type: 'cafe',
    icon: '☕',
    tags: ['Kopi Pontianak', 'Legendaris', 'Murah', 'Buka Pagi', 'Lokal'],
    isFree: false,
    openTime: '05.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Jalan+Merapi+Pontianak',
    description: 'Warung kopi legendaris yang sudah ada puluhan tahun, salah satu yang terbaik di Pontianak. Kopi robusta khas Kalimantan Barat, harga sangat terjangkau. TV dipasang saat ada pertandingan penting, suasana lokal yang autentik.',
  },

  // ── MANADO ──────────────────────────────────────────────────
  {
    id: 'mnd-1',
    name: 'Boulevard Manado',
    city: 'manado',
    address: 'Jl. Piere Tendean, Sario, Manado',
    type: 'outdoor',
    icon: '🌺',
    tags: ['View Teluk Manado', 'Gratis', 'Kuliner', 'Sunset', 'Ikonik'],
    isFree: true,
    openTime: '17.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Boulevard+Manado',
    description: 'Jalan boulevard ikonik Manado yang menghadap Teluk Manado dan Gunung Manado Tua. Komunitas selalu ramai di sini saat pertandingan besar. Puluhan warung makanan khas Manado tersedia sepanjang jalan.',
  },
  {
    id: 'mnd-2',
    name: 'Megamas Manado',
    city: 'manado',
    address: 'Jl. Piere Tendean, Megamas, Manado',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Keluarga', 'Tepi Pantai'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Megamas+Manado',
    description: 'Kawasan mal dan hiburan di tepi pantai Manado. Food court dan restoran memasang layar besar saat pertandingan. Ber-AC, pilihan kuliner khas Manado: tinutuan dan cakalang. View laut langsung.',
  },
  {
    id: 'mnd-3',
    name: 'Kafe Aroma Manado',
    city: 'manado',
    address: 'Jl. Sam Ratulangi, Sario, Manado',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'WiFi', 'Proyektor', 'Kopi Arabika', 'Anak Muda'],
    isFree: false,
    openTime: '09.00–01.00',
    mapsUrl: 'https://maps.google.com/?q=Sam+Ratulangi+Manado',
    description: 'Kafe modern di jantung Manado yang populer di kalangan anak muda dan mahasiswa. Proyektor besar untuk nobar, WiFi kencang, kopi arabika Toraja pilihan. Suasana nyaman, buka sampai dini hari.',
  },

  // ── SAMARINDA ───────────────────────────────────────────────
  {
    id: 'smd-1',
    name: 'Tepian Mahakam Samarinda',
    city: 'samarinda',
    address: 'Jl. Gajah Mada, Samarinda Kota',
    type: 'outdoor',
    icon: '🌿',
    tags: ['View Sungai Mahakam', 'Gratis', 'Ikonik', 'Kuliner', 'Komunitas'],
    isFree: true,
    openTime: '17.00–24.00',
    mapsUrl: 'https://maps.google.com/?q=Tepian+Mahakam+Samarinda',
    description: 'Tepian Sungai Mahakam yang jadi landmark Samarinda. Komunitas bola setempat rutin gelar nobar di area ini saat pertandingan besar. Kuliner khas Kalimantan tersedia, suasana sejuk di tepi sungai.',
  },
  {
    id: 'smd-2',
    name: 'Big Mall Samarinda',
    city: 'samarinda',
    address: 'Jl. Untung Suropati, Samarinda Ulu',
    type: 'mall',
    icon: '🛍️',
    tags: ['AC', 'Food Court', 'Indoor', 'Modern', 'Keluarga'],
    isFree: true,
    openTime: '10.00–22.00',
    mapsUrl: 'https://maps.google.com/?q=Big+Mall+Samarinda',
    description: 'Mal terbesar Samarinda dengan food court lengkap yang memasang layar besar saat ada pertandingan. Ber-AC nyaman, berbagai pilihan kuliner. Parkir luas, mudah diakses dari pusat kota.',
  },
  {
    id: 'smd-3',
    name: 'Taman Cerdas Samarinda',
    city: 'samarinda',
    address: 'Jl. Bhayangkara, Samarinda Ulu',
    type: 'outdoor',
    icon: '🌳',
    tags: ['Gratis', 'Komunitas', 'Layar LED', 'Keluarga', 'Taman Kota'],
    isFree: true,
    openTime: '16.00–23.00',
    mapsUrl: 'https://maps.google.com/?q=Taman+Cerdas+Samarinda',
    description: 'Taman kota modern Samarinda yang jadi pusat aktivitas warga. Layar LED tersedia saat event besar, komunitas bola Samarinda aktif gelar nobar di sini. Fasilitas taman bersih dan terawat, cocok untuk semua usia.',
  },
]

export function getVenuesByCity(citySlug: string): NobarVenue[] {
  return VENUES.filter(v => v.city === citySlug)
}

export function venueSlug(venue: NobarVenue): string {
  return venue.name
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function getVenue(citySlug: string, vSlug: string): NobarVenue | undefined {
  return VENUES.find(v => v.city === citySlug && venueSlug(v) === vSlug)
}

export function getAllVenues(): NobarVenue[] {
  return VENUES
}
